spring:
  datasource:
    url:  jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/${ENV_DATABASE}
    username: ${ENV_USER}
    password: ${ENV_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
